version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - rowserrcheck
  disable:
    - exhaustruct
  settings:
    misspell:
      locale: US
formatters:
  enable:
    - gofmt
    - goimports
